### ISSUE TITLE
JOSS review issues

### ISSUE THREAD

**Issue by layik** [alan-turing-institute/setvis#135]
Reviewer (Kiran) has finalised his review [status](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2231778546). 

Matters outstanding:

**Docs**

Unticked by [Kiran](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2231778546)

- [x] Community guidelines (addressed via various commits)

**Paper**

- [x] agreed in "early Oct" plan
- [x] [summary](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2188151095) which is ticked off by 
[Kiran](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2231778546)

Then latest **comments** by jibalamy
- [x] Community guidelines are very limited in the documentation, and probably need to be enriched (e.g. how to submit bugs or propose help? etc)
- [x] Regarding the paper, it needs more details (and screenshots) to present the various graphics (as I said in a previous message)
- [x] I also tried to run SetVis without Jupyter, but I did not succeed. There is no documentation about that, and actually it is not clear whether it is possible or not. This point should also be clarified. (_I think you can do this better than me @ots22, thank you)_

Latest [comments](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2414170816) by Kiran:
- [x] "A few issue templates on github for bugs, features, etc"
- [x] "A way to contact the devs for support (email or discussions on Github)." package is under Alan Turing Institute account + developer github identities visible.
- [x] "A section to the README for setting up local dev environment, testing, etc." see bold section on README

**Comment by layik** [comment]
Response draft:
- summarise actions in "early Oct" plan
- new contribute.rst in doc, tired up with the guide for generating the docs
- tbc

**Comment by layik** [comment]
Runnig in iPython using `reprexpy`, I believe has been addressed via #133 

```python
from setvis.plots import PlotSession
#> Traceback (most recent call last):
#> Cell In[3], line 1
#> ----> 1 from setvis.plots import PlotSession
#> File ~/code/python/setvis/setvis/plots.py:12
#>      10 from bokeh.palettes import Oranges256
#>      11 from bokeh.transform import linear_cmap
#> ---> 12 from bokeh.models.widgets import Panel, Tabs
#>      13 from bokeh.events import SelectionGeometry
#>      14 import bokeh.io
#> ImportError: cannot import name 'Panel' from 'bokeh.models.widgets' (/home/layik/miniconda3/envs/3point9/lib/python3.9/site-packages/bokeh/models/widgets/__init__.py)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree, preprocessing
#> Traceback (most recent call last):
#> Cell In[7], line 1
#> ----> 1 from sklearn import tree, preprocessing
#> ModuleNotFoundError: No module named 'sklearn'
from sklearn.metrics import mutual_info_score
#> Traceback (most recent call last):
#> Cell In[8], line 1
#> ----> 1 from sklearn.metrics import mutual_info_score
#> ModuleNotFoundError: No module named 'sklearn'
df = pd.read_csv("../examples/datasets/Synthetic_APC_DIAG_Fields.csv")
df.tail()
#>      DIAG_01  DIAG_02  DIAG_03  DIAG_04  DIAG_05  DIAG_06  DIAG_07  DIAG_08  \
195        1      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
196        1      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
197        1      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
198        1      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
199        1      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

     DIAG_09  DIAG_10  ADMIAGE  ADMIMETH  Mortality PROCODE3  SEX  
195      NaN      NaN        8        65          0      abc    1  
196      NaN      NaN       37       111          0      kkk    1  
197      NaN      NaN       10        40          0      fff    2  
198      NaN      NaN       12        65          0      abc    1  
199      NaN      NaN       10       111          0      ggg    2  
session = PlotSession(df)
#> Traceback (most recent call last):
#> Cell In[11], line 1
#> ----> 1 session = PlotSession(df)
#> NameError: name 'PlotSession' is not defined
session.add_plot(name="all data")
#> Traceback (most recent call last):
#> Cell In[12], line 1
#> ----> 1 session.add_plot(name="all data")
#> NameError: name 'session' is not defined
```

**Comment by ots22** [comment]
> I also tried to run SetVis without Jupyter, but I did not succeed. There is no documentation about that, and actually it is not clear whether it is possible or not. This point should also be clarified. (I think you can do this better than me @ots22, thank you)

I think it is reasonable to say that jupyter is the preferred way of using setvis.  We depend on Bokeh for interactive figures so it's hard to replicate the workflow without something like jupyter.

Still, it is possible to start a Bokeh server and return the port, which opens up some possibilities for non-interactive functionality.  That idea is contained in [this example](https://github.com/alan-turing-institute/setvis/blob/main/notebooks/Example%20-%20plotting%20outside%20the%20notebook.ipynb) (fourth cell down), but there isn't much detail on it.

I have been working through the steps of using this and can put a note in the docs: both how to do it if desired, but also that it is 'advanced' usage.

**Comment by layik** [comment]
Thank you very much @ots22, I have just updated the issue inline with the updates in the review thread [latest](https://github.com/openjournals/joss-reviews/issues/6925#issuecomment-2414170816), sending an email now.

**Comment by layik** [comment]
#139

**Comment by ots22** [comment]
PR https://github.com/alan-turing-institute/setvis/pull/140 addresses the comment that it is unclear whether use outside Jupyter is supported

**Comment by layik** [comment]
Thank you @ots22, once #141 is merged, can we please draft a release before I send my review response full draft to the reviewers? Thank you.

**Comment by ots22** [comment]
New release candidate: [GitHub](https://github.com/alan-turing-institute/setvis/releases/tag/v0.1rc5), [PyPI](https://pypi.org/project/setvis/)

**Comment by layik** [comment]
Final review response report sent.

**Comment by layik** [comment]
Recommended to accept, can close this and leave #138 to finalise once paper is published.
